name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    name: Generate Pac-Man graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man contribution graph
        uses: githubocto/repo-visualizer@0.8.2
        with:
          output_file: ./pacman-contribution-graph.svg
          theme: pacman

      - name: Push generated graph to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output
          keep_files: true
